"""initial

Revision ID: c767af967738
Revises: 
Create Date: 2026-09-05 17:03:28.189627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c767af967738'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('operation', sa.String(length=30), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'operation', 'hash', name='uq_ai_cache')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('abbr', sa.String(length=4), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=True)
    op.create_table('otp_challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=80), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenge_phone'), 'otp_challenge', ['phone'], unique=False)
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'ARTISAN', 'BUYER', name='role', native_enum=False, length=16), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    op.create_index(op.f('ix_user_account_phone'), 'user_account', ['phone'], unique=True)
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('line1', sa.String(length=200), nullable=False),
    sa.Column('line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_user_id'), 'address', ['user_id'], unique=False)
    op.create_table('artisan_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('shop_name', sa.String(length=160), nullable=True),
    sa.Column('craft_type', sa.String(length=160), nullable=False),
    sa.Column('cluster_name', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('languages', sa.ARRAY(sa.String(length=10)), nullable=False),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('story_hi', sa.Text(), nullable=True),
    sa.Column('avatar_key', sa.String(length=300), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('bank_account', sa.String(length=40), nullable=True),
    sa.Column('ifsc', sa.String(length=20), nullable=True),
    sa.Column('upi_id', sa.String(length=120), nullable=True),
    sa.Column('kyc_status', sa.Enum('PENDING', 'SUBMITTED', 'VERIFIED', 'REJECTED', name='kycstatus', native_enum=False, length=16), nullable=False),
    sa.Column('kyc_docs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_artisan_profile_kyc_status'), 'artisan_profile', ['kyc_status'], unique=False)
    op.create_index(op.f('ix_artisan_profile_slug'), 'artisan_profile', ['slug'], unique=True)
    op.create_index('ix_artisan_state_district', 'artisan_profile', ['state', 'district'], unique=False)
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('UPI', 'CARD', name='paymenttype', native_enum=False, length=8), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_method_user_id'), 'payment_method', ['user_id'], unique=False)
    op.create_table('stored_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stored_file_key'), 'stored_file', ['key'], unique=True)
    op.create_index(op.f('ix_stored_file_owner_user_id'), 'stored_file', ['owner_user_id'], unique=False)
    op.create_table('customer_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('address_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'RETURNED', 'REFUNDED', name='orderstatus', native_enum=False, length=20), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PROCESSING', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=160), nullable=True),
    sa.Column('payment_type', sa.String(length=8), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tracking_number', sa.String(length=80), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_order_order_number'), 'customer_order', ['order_number'], unique=True)
    op.create_index(op.f('ix_customer_order_user_id'), 'customer_order', ['user_id'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('ENHANCE', 'CATALOG', 'PRICE', name='jobkind', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'FAILED', name='jobstatus', native_enum=False, length=10), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('artisan_id', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisan_profile.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_artisan_id'), 'job', ['artisan_id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_desc', sa.String(length=300), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('compare_at', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sku', sa.String(length=60), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('low_stock', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=160), nullable=True),
    sa.Column('origin', sa.String(length=160), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=True),
    sa.Column('craft', sa.String(length=80), nullable=True),
    sa.Column('craft_technique', sa.String(length=200), nullable=True),
    sa.Column('materials', sa.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('dimensions', sa.String(length=160), nullable=True),
    sa.Column('care_instructions', sa.String(length=300), nullable=True),
    sa.Column('is_handmade', sa.Boolean(), nullable=False),
    sa.Column('gi_tag', sa.String(length=120), nullable=True),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('name_hi', sa.String(length=200), nullable=True),
    sa.Column('short_desc_hi', sa.String(length=300), nullable=True),
    sa.Column('description_hi', sa.Text(), nullable=True),
    sa.Column('bullets', sa.ARRAY(sa.String(length=300)), nullable=False),
    sa.Column('bullets_hi', sa.ARRAY(sa.String(length=300)), nullable=False),
    sa.Column('seo_keywords', sa.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('ai_status', sa.Enum('NONE', 'DRAFT', 'AI_ENHANCED', 'PUBLISHED', name='aistatus', native_enum=False, length=16), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisan_profile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('ix_product_active_featured', 'product', ['is_active', 'is_featured'], unique=False)
    op.create_index(op.f('ix_product_artisan_id'), 'product', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_slug'), 'product', ['slug'], unique=True)
    op.create_index('ix_product_synthetic', 'product', ['is_synthetic'], unique=False)
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', name='uq_cart_product')
    )
    op.create_index(op.f('ix_cart_item_cart_id'), 'cart_item', ['cart_id'], unique=False)
    op.create_table('enquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quoted_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'QUOTED', 'ACCEPTED', 'DECLINED', 'CLOSED', name='enquirystatus', native_enum=False, length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisan_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyer_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiry_artisan_id'), 'enquiry', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_enquiry_buyer_id'), 'enquiry', ['buyer_id'], unique=False)
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('artisan_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisan_profile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['customer_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_artisan_id'), 'order_item', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_item_product_id'), 'order_item', ['product_id'], unique=False)
    op.create_table('price_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fair', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('premium', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('rationale_hi', sa.Text(), nullable=True),
    sa.Column('comparables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accepted', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisan_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_suggestion_artisan_id'), 'price_suggestion', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_price_suggestion_product_id'), 'price_suggestion', ['product_id'], unique=False)
    op.create_table('product_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_comment_product_id'), 'product_comment', ['product_id'], unique=False)
    op.create_table('product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('alt', sa.String(length=200), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('original_key', sa.String(length=300), nullable=True),
    sa.Column('enhanced_key', sa.String(length=300), nullable=True),
    sa.Column('enhance_status', sa.Enum('NONE', 'QUEUED', 'DONE', 'FAILED', name='enhancestatus', native_enum=False, length=16), nullable=False),
    sa.Column('qc_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_image_product_id'), 'product_image', ['product_id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'user_id', name='uq_review_product_user')
    )
    op.create_index(op.f('ix_review_product_id'), 'review', ['product_id'], unique=False)
    op.create_table('voice_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('audio_key', sa.String(length=300), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_en', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'FAILED', name='jobstatus', native_enum=False, length=10), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisan_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_note_artisan_id'), 'voice_note', ['artisan_id'], unique=False)
    op.create_table('wishlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_wishlist_user_product')
    )
    op.create_index(op.f('ix_wishlist_item_user_id'), 'wishlist_item', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlist_item_user_id'), table_name='wishlist_item')
    op.drop_table('wishlist_item')
    op.drop_index(op.f('ix_voice_note_artisan_id'), table_name='voice_note')
    op.drop_table('voice_note')
    op.drop_index(op.f('ix_review_product_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_product_image_product_id'), table_name='product_image')
    op.drop_table('product_image')
    op.drop_index(op.f('ix_product_comment_product_id'), table_name='product_comment')
    op.drop_table('product_comment')
    op.drop_index(op.f('ix_price_suggestion_product_id'), table_name='price_suggestion')
    op.drop_index(op.f('ix_price_suggestion_artisan_id'), table_name='price_suggestion')
    op.drop_table('price_suggestion')
    op.drop_index(op.f('ix_order_item_product_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_item_artisan_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_enquiry_buyer_id'), table_name='enquiry')
    op.drop_index(op.f('ix_enquiry_artisan_id'), table_name='enquiry')
    op.drop_table('enquiry')
    op.drop_index(op.f('ix_cart_item_cart_id'), table_name='cart_item')
    op.drop_table('cart_item')
    op.drop_index('ix_product_synthetic', table_name='product')
    op.drop_index(op.f('ix_product_slug'), table_name='product')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_index(op.f('ix_product_artisan_id'), table_name='product')
    op.drop_index('ix_product_active_featured', table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_job_artisan_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_customer_order_user_id'), table_name='customer_order')
    op.drop_index(op.f('ix_customer_order_order_number'), table_name='customer_order')
    op.drop_table('customer_order')
    op.drop_index(op.f('ix_stored_file_owner_user_id'), table_name='stored_file')
    op.drop_index(op.f('ix_stored_file_key'), table_name='stored_file')
    op.drop_table('stored_file')
    op.drop_index(op.f('ix_payment_method_user_id'), table_name='payment_method')
    op.drop_table('payment_method')
    op.drop_table('cart')
    op.drop_index('ix_artisan_state_district', table_name='artisan_profile')
    op.drop_index(op.f('ix_artisan_profile_slug'), table_name='artisan_profile')
    op.drop_index(op.f('ix_artisan_profile_kyc_status'), table_name='artisan_profile')
    op.drop_table('artisan_profile')
    op.drop_index(op.f('ix_address_user_id'), table_name='address')
    op.drop_table('address')
    op.drop_index(op.f('ix_user_account_phone'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_index(op.f('ix_otp_challenge_phone'), table_name='otp_challenge')
    op.drop_table('otp_challenge')
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.drop_table('category')
    op.drop_table('ai_cache')
    # ### end Alembic commands ###
